spring:
  application:
    name: oauth2-demo
  security:
    user:
      name: admin
      password: admin
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope: read:user,user:email
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
  datasource:
    url: jdbc:mysql://localhost:3306/oauth_db?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Mysql@root
    driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
      hibernate:
        ddl-auto: create
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          id:
            new_generator_mappings: true
          format_sql: true

  logging:
    level:
      org.springframework.security: DEBUG
      org.hibernate.SQL: debug
      org.hibernate.tool.hbm2ddl: debug
      org.hibernate.type.descriptor.sql: trace